# Set path to your private settings directory
private_settings_dir: ~/private_settings/ssh/templates/

# Set your git email and name
git_email: "mymail@mail.com"
git_name: "My Name"

# Install yum packages
install_yum_packages: true

ssh_config_values:
  - host: "github.com"
    host_name: "github.com"
    user: "git"
    port: 22
    identity_file: "~/.ssh/id_rsa_github"
    keep_alive: "yes"
    identities_only: "yes"
  # - host: "sub.github.com"
  #   host_name: "sub.github.com"
  #   user: "git"
  #   port: 22
  #   identity_file: "~/.ssh/id_rsa_github_sub"
  #   keep_alive: "yes"
  #   identities_only: "yes"
